"""
Tool: search the 4C test file catalog.

Provides a lightweight search function over the pre-built catalog of ~1,986
test input files (.4C.yaml). The catalog is generated by
scripts/catalog_test_files.py and stored at data/test_file_catalog.json.

Each catalog entry contains:
  - path: relative path from 4C root
  - problem_type: e.g. "Structure", "Fluid", "Scalar_Transport"
  - description: from TITLE section if present
  - has_dirichlet: boolean
  - has_neumann: boolean
  - mesh_file: external mesh file name if present
  - material_types: list of material keys (e.g. ["MAT_scatra", "ELAST_CoupNeoHooke"])
  - solver_type: SOLVER 1 solver type (e.g. "UMFPACK", "Belos", "Superlu")
  - is_stationary: boolean (Statics/Stationary time integration)
  - element_types: list of element types (e.g. ["HEX8", "TET4"])
"""

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

logger = logging.getLogger("fourc-mcp.catalog")

# Path to the catalog JSON file
_CATALOG_DIR = Path(__file__).resolve().parents[2] / "data"
_CATALOG_FILE = _CATALOG_DIR / "test_file_catalog.json"

# Cached catalog data
_catalog_cache: Optional[Dict[str, Any]] = None


def _load_catalog() -> Dict[str, Any]:
    """Load the catalog from JSON, with caching."""
    global _catalog_cache
    if _catalog_cache is not None:
        return _catalog_cache

    if not _CATALOG_FILE.exists():
        raise FileNotFoundError(
            f"Catalog not found at {_CATALOG_FILE}. "
            "Run 'python scripts/catalog_test_files.py' to generate it."
        )

    with open(_CATALOG_FILE, "r", encoding="utf-8") as f:
        _catalog_cache = json.load(f)

    logger.info(
        "Loaded catalog with %d files",
        _catalog_cache.get("metadata", {}).get("total_files", 0),
    )
    return _catalog_cache


def get_catalog_metadata() -> Dict[str, Any]:
    """Return catalog metadata (total files, source directory, etc.)."""
    catalog = _load_catalog()
    return catalog.get("metadata", {})


def search_catalog(
    query: Optional[str] = None,
    *,
    problem_type: Optional[str] = None,
    material_type: Optional[str] = None,
    element_type: Optional[str] = None,
    solver_type: Optional[str] = None,
    has_dirichlet: Optional[bool] = None,
    has_neumann: Optional[bool] = None,
    is_stationary: Optional[bool] = None,
    has_mesh_file: Optional[bool] = None,
    path_contains: Optional[str] = None,
    max_results: int = 50,
) -> List[Dict[str, Any]]:
    """
    Search the test file catalog with optional filters.

    Parameters
    ----------
    query : str, optional
        Free-text query matched against path, description, and material types.
        Case-insensitive substring match.
    problem_type : str, optional
        Filter by problem type (case-insensitive substring match).
        Examples: "Structure", "Fluid", "Scalar_Transport", "Poroelasticity"
    material_type : str, optional
        Filter by material type key (case-insensitive substring match).
        Examples: "MAT_scatra", "ElastHyper", "electrode"
    element_type : str, optional
        Filter by element type (case-insensitive exact match).
        Examples: "HEX8", "TET4", "QUAD4", "LINE2"
    solver_type : str, optional
        Filter by solver type (case-insensitive substring match).
        Examples: "UMFPACK", "Belos", "Superlu"
    has_dirichlet : bool, optional
        If True, only return files with Dirichlet conditions.
    has_neumann : bool, optional
        If True, only return files with Neumann conditions.
    is_stationary : bool, optional
        If True, only return stationary/static simulations.
    has_mesh_file : bool, optional
        If True, only return files referencing an external mesh.
    path_contains : str, optional
        Filter by substring in the file path (case-insensitive).
    max_results : int
        Maximum number of results to return (default: 50).

    Returns
    -------
    list of dict
        Matching catalog entries, each with keys: path, problem_type,
        description, has_dirichlet, has_neumann, mesh_file, material_types,
        solver_type, is_stationary, element_types.

    Examples
    --------
    >>> # Find all fluid simulations with HEX8 elements
    >>> results = search_catalog(problem_type="Fluid", element_type="HEX8")

    >>> # Find all files using Neo-Hookean materials
    >>> results = search_catalog(material_type="NeoHooke")

    >>> # Free-text search for "contact"
    >>> results = search_catalog("contact")

    >>> # Find stationary scalar transport problems
    >>> results = search_catalog(problem_type="Scalar_Transport", is_stationary=True)
    """
    catalog = _load_catalog()
    files = catalog.get("files", [])
    results = []

    for entry in files:
        # Apply filters
        if problem_type is not None:
            pt = entry.get("problem_type") or ""
            if problem_type.lower() not in pt.lower():
                continue

        if material_type is not None:
            mat_types = entry.get("material_types", [])
            if not any(material_type.lower() in mt.lower() for mt in mat_types):
                continue

        if element_type is not None:
            elem_types = entry.get("element_types", [])
            if element_type.upper() not in [et.upper() for et in elem_types]:
                continue

        if solver_type is not None:
            st = entry.get("solver_type") or ""
            if solver_type.lower() not in st.lower():
                continue

        if has_dirichlet is not None:
            if entry.get("has_dirichlet") != has_dirichlet:
                continue

        if has_neumann is not None:
            if entry.get("has_neumann") != has_neumann:
                continue

        if is_stationary is not None:
            if entry.get("is_stationary") != is_stationary:
                continue

        if has_mesh_file is not None:
            has_mesh = entry.get("mesh_file") is not None
            if has_mesh != has_mesh_file:
                continue

        if path_contains is not None:
            path = entry.get("path") or ""
            if path_contains.lower() not in path.lower():
                continue

        if query is not None:
            q = query.lower()
            searchable = " ".join([
                entry.get("path") or "",
                entry.get("description") or "",
                entry.get("problem_type") or "",
                " ".join(entry.get("material_types", [])),
                " ".join(entry.get("element_types", [])),
                entry.get("solver_type") or "",
            ]).lower()
            if q not in searchable:
                continue

        results.append(entry)
        if len(results) >= max_results:
            break

    return results


def list_problem_types() -> Dict[str, int]:
    """Return a dict of problem_type -> count across all cataloged files."""
    catalog = _load_catalog()
    counts: Dict[str, int] = {}
    for entry in catalog.get("files", []):
        pt = entry.get("problem_type") or "UNKNOWN"
        counts[pt] = counts.get(pt, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: -x[1]))


def list_material_types() -> Dict[str, int]:
    """Return a dict of material_type -> count across all cataloged files."""
    catalog = _load_catalog()
    counts: Dict[str, int] = {}
    for entry in catalog.get("files", []):
        for mt in entry.get("material_types", []):
            counts[mt] = counts.get(mt, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: -x[1]))


def list_element_types() -> Dict[str, int]:
    """Return a dict of element_type -> count across all cataloged files."""
    catalog = _load_catalog()
    counts: Dict[str, int] = {}
    for entry in catalog.get("files", []):
        for et in entry.get("element_types", []):
            counts[et] = counts.get(et, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: -x[1]))


def list_solver_types() -> Dict[str, int]:
    """Return a dict of solver_type -> count across all cataloged files."""
    catalog = _load_catalog()
    counts: Dict[str, int] = {}
    for entry in catalog.get("files", []):
        st = entry.get("solver_type") or "UNKNOWN"
        counts[st] = counts.get(st, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: -x[1]))


def get_file_entry(path: str) -> Optional[Dict[str, Any]]:
    """Look up a specific file by its path (or path substring)."""
    catalog = _load_catalog()
    for entry in catalog.get("files", []):
        if path in entry.get("path", ""):
            return entry
    return None


# ---------------------------------------------------------------------------
# CLI: allow running this module directly to test searches
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import argparse
    import sys

    parser = argparse.ArgumentParser(
        description="Search the 4C test file catalog"
    )
    parser.add_argument("query", nargs="?", help="Free-text search query")
    parser.add_argument("--problem-type", "-p", help="Filter by problem type")
    parser.add_argument("--material-type", "-m", help="Filter by material type")
    parser.add_argument("--element-type", "-e", help="Filter by element type")
    parser.add_argument("--solver-type", "-s", help="Filter by solver type")
    parser.add_argument("--stationary", action="store_true", help="Only stationary")
    parser.add_argument("--max-results", "-n", type=int, default=20)
    parser.add_argument("--list-types", action="store_true",
                        help="List all problem/material/element types and counts")

    args = parser.parse_args()

    if args.list_types:
        print("\n=== Problem Types ===")
        for pt, count in list_problem_types().items():
            print(f"  {pt:45s} {count:5d}")
        print("\n=== Material Types (top 30) ===")
        for i, (mt, count) in enumerate(list_material_types().items()):
            if i >= 30:
                break
            print(f"  {mt:45s} {count:5d}")
        print("\n=== Element Types ===")
        for et, count in list_element_types().items():
            print(f"  {et:45s} {count:5d}")
        print("\n=== Solver Types ===")
        for st, count in list_solver_types().items():
            print(f"  {st:45s} {count:5d}")
        sys.exit(0)

    results = search_catalog(
        query=args.query,
        problem_type=args.problem_type,
        material_type=args.material_type,
        element_type=args.element_type,
        solver_type=args.solver_type,
        is_stationary=args.stationary or None,
        max_results=args.max_results,
    )

    print(f"Found {len(results)} results:")
    for entry in results:
        pt = entry.get("problem_type") or "?"
        desc = entry.get("description") or ""
        if desc and len(desc) > 60:
            desc = desc[:57] + "..."
        mats = ", ".join(entry.get("material_types", [])[:3])
        elems = ", ".join(entry.get("element_types", [])[:3])
        print(f"\n  {entry['path']}")
        print(f"    type={pt}  solver={entry.get('solver_type', '?')}")
        if mats:
            print(f"    materials: {mats}")
        if elems:
            print(f"    elements: {elems}")
        if desc:
            print(f"    desc: {desc}")
