"""
preCICE XML configuration generator for cross-solver coupling.

Generates preCICE-config.xml for standard coupling scenarios.
This enables comparison between our MCP-orchestrated DN coupling
and preCICE's native coupling infrastructure.

preCICE is NOT required for the Open FEM Agent to work — this module
generates configurations for optional comparison studies.
"""

import logging
from pathlib import Path

logger = logging.getLogger("open-fem-agent.precice")


def check_precice_available() -> tuple[bool, str]:
    """Check if preCICE Python bindings are installed."""
    try:
        import precice
        return True, f"preCICE {precice.__version__}"
    except ImportError:
        return False, (
            "preCICE not installed. Install via: "
            "pip install pyprecice (requires libprecice C++ library)"
        )


def generate_heat_coupling_config(
    mesh_name_a: str = "FEniCS-Mesh",
    mesh_name_b: str = "4C-Mesh",
    data_name: str = "Temperature",
    flux_name: str = "Heat-Flux",
    max_iterations: int = 20,
    convergence_tol: float = 1e-6,
    relaxation: float = 0.5,
    time_window: float = 1.0,
    output_dir: str = "precice-output",
) -> str:
    """Generate preCICE XML config for Dirichlet-Neumann heat coupling.

    This produces a configuration equivalent to our MCP-orchestrated DN
    domain decomposition, enabling direct comparison.

    Args:
        mesh_name_a: Mesh name for the Dirichlet participant (FEniCS).
        mesh_name_b: Mesh name for the Neumann participant (4C).
        data_name: Name of the temperature data field.
        flux_name: Name of the heat flux data field.
        max_iterations: Maximum implicit coupling iterations.
        convergence_tol: Convergence criterion for the coupling.
        relaxation: Initial relaxation factor for Aitken acceleration.
        time_window: Size of coupling time window.
        output_dir: Directory for preCICE output.

    Returns:
        Complete preCICE XML configuration as a string.
    """
    return f"""\
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
  <!-- preCICE config for DN heat coupling — generated by Open FEM Agent -->

  <log>
    <sink type="stream" output="stdout" filter="%Severity% > debug"
          format="%ColorizedSeverity% %Message%" enabled="true" />
  </log>

  <data:scalar name="{data_name}" />
  <data:scalar name="{flux_name}" />

  <mesh name="{mesh_name_a}" dimensions="2">
    <use-data name="{data_name}" />
    <use-data name="{flux_name}" />
  </mesh>

  <mesh name="{mesh_name_b}" dimensions="2">
    <use-data name="{data_name}" />
    <use-data name="{flux_name}" />
  </mesh>

  <!-- Dirichlet participant (FEniCS): writes temperature, reads flux -->
  <participant name="Dirichlet">
    <provide-mesh name="{mesh_name_a}" />
    <receive-mesh name="{mesh_name_b}" from="Neumann" />
    <write-data name="{data_name}" mesh="{mesh_name_a}" />
    <read-data name="{flux_name}" mesh="{mesh_name_a}" />
    <mapping:nearest-neighbor direction="read"
      from="{mesh_name_b}" to="{mesh_name_a}"
      constraint="consistent" />
  </participant>

  <!-- Neumann participant (4C): reads temperature, writes flux -->
  <participant name="Neumann">
    <provide-mesh name="{mesh_name_b}" />
    <receive-mesh name="{mesh_name_a}" from="Dirichlet" />
    <write-data name="{flux_name}" mesh="{mesh_name_b}" />
    <read-data name="{data_name}" mesh="{mesh_name_b}" />
    <mapping:nearest-neighbor direction="read"
      from="{mesh_name_a}" to="{mesh_name_b}"
      constraint="consistent" />
  </participant>

  <m2n:sockets acceptor="Dirichlet" connector="Neumann"
    exchange-directory=".." />

  <coupling-scheme:serial-implicit>
    <time-window-size value="{time_window}" />
    <max-time value="{time_window}" />
    <participants first="Dirichlet" second="Neumann" />
    <exchange data="{data_name}" mesh="{mesh_name_a}"
      from="Dirichlet" to="Neumann" />
    <exchange data="{flux_name}" mesh="{mesh_name_b}"
      from="Neumann" to="Dirichlet" />
    <max-iterations value="{max_iterations}" />
    <relative-convergence-measure limit="{convergence_tol}"
      data="{data_name}" mesh="{mesh_name_a}" />
    <acceleration:aitken>
      <data mesh="{mesh_name_a}" name="{data_name}" />
      <initial-relaxation value="{relaxation}" />
    </acceleration:aitken>
  </coupling-scheme:serial-implicit>
</precice-configuration>
"""


def generate_tsi_coupling_config(
    mesh_name_a: str = "Thermal-Mesh",
    mesh_name_b: str = "Structure-Mesh",
    temperature_name: str = "Temperature",
    displacement_name: str = "Displacement",
    heat_flux_name: str = "Heat-Flux",
    traction_name: str = "Force",
    max_iterations: int = 30,
    convergence_tol: float = 1e-6,
    time_window: float = 1.0,
) -> str:
    """Generate preCICE XML for thermal-structural interaction coupling.

    Two-way coupling: temperature and displacement exchanged between solvers.

    Returns:
        Complete preCICE XML configuration string.
    """
    return f"""\
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
  <!-- preCICE config for TSI coupling — generated by Open FEM Agent -->

  <log>
    <sink type="stream" output="stdout" filter="%Severity% > debug"
          format="%ColorizedSeverity% %Message%" enabled="true" />
  </log>

  <data:scalar name="{temperature_name}" />
  <data:vector name="{displacement_name}" />
  <data:scalar name="{heat_flux_name}" />

  <mesh name="{mesh_name_a}" dimensions="3">
    <use-data name="{temperature_name}" />
    <use-data name="{heat_flux_name}" />
  </mesh>

  <mesh name="{mesh_name_b}" dimensions="3">
    <use-data name="{temperature_name}" />
    <use-data name="{displacement_name}" />
  </mesh>

  <!-- Thermal solver: provides temperature, receives heat flux -->
  <participant name="Thermal">
    <provide-mesh name="{mesh_name_a}" />
    <receive-mesh name="{mesh_name_b}" from="Structure" />
    <write-data name="{temperature_name}" mesh="{mesh_name_a}" />
    <read-data name="{heat_flux_name}" mesh="{mesh_name_a}" />
    <mapping:nearest-neighbor direction="read"
      from="{mesh_name_b}" to="{mesh_name_a}"
      constraint="consistent" />
  </participant>

  <!-- Structural solver: reads temperature, provides displacement -->
  <participant name="Structure">
    <provide-mesh name="{mesh_name_b}" />
    <receive-mesh name="{mesh_name_a}" from="Thermal" />
    <read-data name="{temperature_name}" mesh="{mesh_name_b}" />
    <write-data name="{displacement_name}" mesh="{mesh_name_b}" />
    <mapping:nearest-neighbor direction="read"
      from="{mesh_name_a}" to="{mesh_name_b}"
      constraint="consistent" />
  </participant>

  <m2n:sockets acceptor="Thermal" connector="Structure"
    exchange-directory=".." />

  <coupling-scheme:serial-implicit>
    <time-window-size value="{time_window}" />
    <max-time value="{time_window}" />
    <participants first="Thermal" second="Structure" />
    <exchange data="{temperature_name}" mesh="{mesh_name_a}"
      from="Thermal" to="Structure" />
    <exchange data="{displacement_name}" mesh="{mesh_name_b}"
      from="Structure" to="Thermal" />
    <max-iterations value="{max_iterations}" />
    <relative-convergence-measure limit="{convergence_tol}"
      data="{temperature_name}" mesh="{mesh_name_a}" />
    <acceleration:aitken>
      <data mesh="{mesh_name_a}" name="{temperature_name}" />
      <initial-relaxation value="0.5" />
    </acceleration:aitken>
  </coupling-scheme:serial-implicit>
</precice-configuration>
"""


def save_precice_config(config_xml: str, output_dir: Path, filename: str = "precice-config.xml") -> Path:
    """Save preCICE configuration to file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / filename
    path.write_text(config_xml)
    logger.info(f"preCICE config saved to {path}")
    return path
